### PR TITLE
Sanitize IPsec key after setting config (#86)

### PR DESCRIPTION
**Pull request by ffoulkes**
- Implement wrapper class to sanitize key field in sadb_config object.

- Use clang-format to fix line wrapping and indentation.

### CODE REVIEW

**Comment by 5abeel** [comment]
This looks like a new commit instead of cherry-picking the commit that went into `split-arch`
If we decide to merge more & see diffs between the branches, we may see clashes. Ideally we should cherry-pick the same commit if possible

**Comment by ffoulkes** [comment]
> This looks like a new commit instead of cherry-picking the commit that went into `split-arch` If we decide to merge more & see diffs between the branches, we may see clashes. Ideally we should cherry-pick the same commit if possible

This commit was created by creating a topic branch based on ipdk_23.07, cherry-picking the commit from the split-arch branch, editing it to resolve the differences, pushing the topic branch to the server, and generating a PR. What would you have done differently?

In the split-arch branch, we only had to update one repository because we had moved most of the cmake build into the stratum-dev repository in a previous commit. In the ipdk_23.07 branch, the Stratum cmake files are still in the networking-recipe repository, so it takes commits to two repositories to accomplish the same thing.

The hassle of updating stratum in one repo and its cmake files in another is precisely why we moved them.

You're correct, future merges from the trunk branch into the 23.07 branch may see clashes. Fortunately, the plan is to make a limited number of changes to 23.07, so this may not happen.

**Review by 5abeel — APPROVED** [review]
LGTM

**Review by nupuruttarwar — APPROVED** [review]
LGTM

**Pull request merged**
