### PR TITLE
Stratum cmake support

### PR DESCRIPTION
**Pull request by ffoulkes**
- Implement basic CMake build support for TDI (IPDK) targets.

### CODE REVIEW

**Comment by ffoulkes** [comment]
This PR is substantially the same as one made by @ravi861 in November 2022 (https://github.com/ipdk-io/stratum-dev/pull/28).

The current plan is to wait until after the 23.07 release to incorporate this change.

**Review by ravi861 — COMMENTED** [review]
LGTM

**Comment by ffoulkes** [comment]
We really should go ahead and merge these changes. They simplify future updates considerably.

**Review by nupuruttarwar — APPROVED** [review]
LGTM

**Review by satish153 — APPROVED** [review]
LGTM

**Pull request merged**
