### PR TITLE
Apply upstream changes to hal/lib/phal

### PR DESCRIPTION
**Pull request by ffoulkes**
- Convert CHECK_RETURN_IF_FALSE() to RET_CHECK().

- Canonicalize C++ source with clang-format.

### CODE REVIEW

**Comment by 5abeel** [comment]
Minor comment: We probably need to update the Copyright 2023 update on all the edited files in this CL

**Comment by ffoulkes** [comment]
> Minor comment: We probably need to update the Copyright 2023 update on all the edited files in this CL

This CL consists of updates merged from the upstream repository. These changes are covered by the ONF copyright.

You have a good point, though. We (I) need to remember this when applying global upstream changes (such as replacing `CHECK_RETURN_IF_FALSE()` with `RET_CHECK()`) to the files we're contributing to Stratum.

**Review by 5abeel — APPROVED** [review]
LGTM

**Review by nupuruttarwar — APPROVED** [review]
LGTM

**Pull request merged**
