### PR TITLE
Make -client_cert_req_type case-insensitive

### PR DESCRIPTION
**Pull request by ffoulkes**
- Having to change case in the middle of typing a command is a nuisance. "Be liberal in what you accept from others."

### CODE REVIEW

**Review by 5abeel — APPROVED** [review]
LGTM

**Comment by ffoulkes** [comment]
Realized belatedly that I have should have checked Abseil for a ToLower() function.
Found one.
Better now.

**Review by 5abeel — APPROVED** [review]

**Review by nupuruttarwar — APPROVED** [review]
LGTM

**Review by aashishkuma — APPROVED** [review]
LGTM

**Review by vsureshkumarp — APPROVED** [review]
LGTM..:)

**Pull request merged**
