### PR TITLE
"bf_" name change in stratum

### PR DESCRIPTION
**Pull request by aashishkuma**
This underlying P4SDE for ES2K target is renaming bf_swtichd to ipu_p4d.
The P4SDE changes are:
https://github.com/intel-innersource/networking.ethernet.acceleration.vswitch.p4-sde.p4-driver/tree/rename-bf

This PR contains the changes required in the stratum module to build ES2K target with the underlying P4SDE change.
Since, some of the files that are impacted with the P4SDE change are common to the compilation of both dpdk and es2k targets, hence I have introduced target specific macro check to avoid it's compilation for the other target.

Note:
The related changes are expected in stratum modules, krnlmon module and the main networking recipe repo.

### CODE REVIEW

**Review by ffoulkes — CHANGES_REQUESTED** [review]
There's a right way and a wrong way to make changes in the public interface between components.

This is categorically the wrong way. It is irresponsible, unprofessional, and disruptive, and it seriously compromises the quality and maintainability of the software.

We need to push back on this for the good of the project.

**Comment by ffoulkes** [comment]
The bad news:
1. This CL is based on an older version of the Stratum code that has not been updated to fix the Bazel build. It needs to be rebased on the latest version of the `split-arch` branch.
2. We went to considerable effort to remove all target-specific #ifdefs from the Stratum code. This CL reintroduces them.
   - They increase cognitive load, making the code more difficult to maintain.
   - They increase technical debt.
   - They are inconsistent with Stratum design principles.
   - They represent a regression in the quality of the code.
   - I believe they break the ES2K Bazel build (though I cannot currently confirm this).
4. Any new or modified source files must be run through clang-format (`clang-format -i <filenames>`) to ensure that the files conform to the Stratum coding standard. (Note that the clang-format checker in the GitHub workflow has blocked this commit due to errors.)
5. Further changes may be needed once the `stratum-changes` branch has been merged into `split-arch`.

**Comment by ffoulkes** [comment]
The good news:

Once the branch had been rebased on `split-arch`,

1. The Barefoot Bazel build succeeded.
2. The legacy platform (barefoot, bcm, dummy, np4intel) unit tests passed, with one minor modification.
   - Note that I'm not currently set up to test the bmv2 platform.
4. The Tofino Bazel build and unit tests passed.
5. The DPDK Bazel build and unit tests passed.
6. The cdlang test suite passed.

I'm unable to run the ES2K Bazel build and unit tests without an updated SDE. As noted in the Bad News comment, I suspect that the ES2K #ifdefs will cause Bazel build failures.

**Review by ffoulkes — APPROVED** [review]
Objections withdrawn. I have been instructed to approve this PR.

**Review by nupuruttarwar — APPROVED** [review]
LGTM

**Pull request merged**
