### PR TITLE
Remove MVLUT-specific changes from Stratum

### PR DESCRIPTION
**Pull request by n-sandeep**
Because we are updating the p4runtime submodule to pick from latest p4runtime and ignoring custom changes made to p4runtime.proto and p4info.proto to support Match Value Lookup, we will not have the definitions of MvLUT in the autogenerated p4runtime.pb.h/.cc files. This causes a build failure.

These changes are made to remove all LUT specific changes in stratum. WriteExtern API is kept intact so that future Meter changes can go in there.

### CODE REVIEW

**Comment by ffoulkes** [comment]
This CL breaks both `bazel build` and `bazel test` for the ES2K target.

In `stratum/hal/lib/tdi/BUILD`:

- Remove `:tdi_lut_manager` from the `tdi_node` target
- Remove the `tdi_lut_manager` target
- Remove the `tdi_lut_manager_test` target

To verify:

- `bazel build //stratum/hal/bin/tdi/es2k/stratum_es2k --define target=es2k`
- `bazel test //stratum/hal/lib/tdi:all --define target=es2k`

-----

This CL also breaks the cmake build.

In `stratum/CMakeLists.txt`:

- Remove `tdi_lut_manager.cc` and `tdi_lut_manager.h` from the `stratum_tdi_common_o` target

To verify:
- `./build-all --target=es2k`

You'll need to generate a networking-recipe PR to commit this.

-----

Are we completely done with `tdi_lut_manager`? If so, we should delete the source and test files.

-----

Are there accompanying changes in P4Runtime?

- If so, we need to generate a new Python wheel or delete the existing one.

**Review by ffoulkes — CHANGES_REQUESTED** [review]
Need to:
1. Fix Bazel build and test in this PR
2. Fix CMake build in an accompanying PR
3. Make accompanying changes in Python wheel?
4. Update stratum submodule pointer when updating CMake build
5. Update P4Runtime submodule pointer?

See separate note for details.

**Comment by n-sandeep** [comment]
> 

I have built locally by removing lut_manager files from networking-recipe/stratum/CMakeLists.txt. This will go in a seperate PR which will be raised in networking-recipe repo : https://github.com/ipdk-io/networking-recipe/pull/157

But I have kept tdi_lut_manager.h and tdi_lut_manager.cc files on purpose, because tdi_lut_manager_test file was written initially for these files and didnt want to remove the reference test file that was written.

Sure Derek,  as suggested, will test bazel build, and update https://github.com/ipdk-io/networking-recipe/pull/157 with p4runtime submodule + its SHA, stratum SHA.

**Comment by n-sandeep** [comment]
@ffoulkes , i have updated PR by deleting LUT manager reference code and also removed from bazel build and tests.
I have locally ran Bazel tests, it has passed.
Though local bazel source code build failed with STRLCPY definition from libdriver.so

**Review by ffoulkes — APPROVED** [review]
LGTM

The `strlcpy` issue appears to be is a product of using a newer SDE on Fedora. It has no bearing on the commit itself.

The actual merge depends on all the moving parts being in place, so we don't leave the code base in a broken state.

**Review by vsureshkumarp — APPROVED** [review]
Changes looks good to me.

**Pull request merged**
